/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a tcbtphone_adaptor.h: ../dbus_xml_config/Semisky.BlueToothMidware.TcBtPhone.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TCBTPHONE_ADAPTOR_H
#define TCBTPHONE_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface smk.tcc8971.BlueToothMidware.TcBtPhone
 */
class TcBtPhoneAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "smk.tcc8971.BlueToothMidware.TcBtPhone")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"smk.tcc8971.BlueToothMidware.TcBtPhone\">\n"
"    <method name=\"sysActivate\"/>\n"
"    <method name=\"sysDeactivate\"/>\n"
"    <method name=\"deviceSearchStart\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"totalSearchTime\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"maxDevices\"/>\n"
"    </method>\n"
"    <method name=\"deviceSearchCancel\"/>\n"
"    <method name=\"deviceConnect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"DeviceNum\"/>\n"
"    </method>\n"
"    <method name=\"deviceDisconnect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"DeviceNum\"/>\n"
"    </method>\n"
"    <method name=\"deviceDelete\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"DeviceNum\"/>\n"
"    </method>\n"
"    <method name=\"deviceAllDelete\"/>\n"
"    <method name=\"deviceCompareornot\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"bAccept\"/>\n"
"    </method>\n"
"    <method name=\"getContactInfo\"/>\n"
"    <method name=\"getHistoryCalInfo\"/>\n"
"    <method name=\"cmdDialByNum\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"contactPhNum\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"numSize\"/>\n"
"    </method>\n"
"    <method name=\"cmdDialByName\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"contactName\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"numSize\"/>\n"
"    </method>\n"
"    <method name=\"cmdReDial\"/>\n"
"    <method name=\"cmdIncomingAnswer\"/>\n"
"    <method name=\"cmdIncomingReject\"/>\n"
"    <method name=\"cmdEndCal\"/>\n"
"    <method name=\"cmdHangUp\"/>\n"
"    <method name=\"cmdNumBtnClicked\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"Num\"/>\n"
"    </method>\n"
"    <method name=\"cmdChangeVoiceMode\"/>\n"
"    <method name=\"cmdSetVoiceMute\"/>\n"
"    <method name=\"cmdVoiceRecognition\"/>\n"
"    <method name=\"cmdOpenPhoneAudio\"/>\n"
"    <method name=\"cmdStartOutgoingCall\"/>\n"
"    <method name=\"cmdStartIncomingCall\"/>\n"
"    <signal name=\"initBtappSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceAddr\"/>\n"
"    </signal>\n"
"    <signal name=\"initBtappFaile\"/>\n"
"    <signal name=\"deInitBtappSuccess\"/>\n"
"    <signal name=\"deviceCompare\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"passCode\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceAddr\"/>\n"
"    </signal>\n"
"    <signal name=\"deviceConnectSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceAddr\"/>\n"
"    </signal>\n"
"    <signal name=\"deviceDisConnectSuccess\"/>\n"
"    <signal name=\"deviceConnectFaile\"/>\n"
"    <signal name=\"deviceSearchSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"deviceName\"/>\n"
"    </signal>\n"
"    <signal name=\"deviceSearchClosed\"/>\n"
"    <signal name=\"deviceDeleteSuccess\"/>\n"
"    <signal name=\"getContactsSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"contactName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"homeNum\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"workNum\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"otherNum\"/>\n"
"    </signal>\n"
"    <signal name=\"getContactsFaile\"/>\n"
"    <signal name=\"getContactsEnd\"/>\n"
"    <signal name=\"getHisCallSuccess\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"hisCallname\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"hisCallnum\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"hisCalltime\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"hisCalltype\"/>\n"
"    </signal>\n"
"    <signal name=\"getHisCallFaile\"/>\n"
"    <signal name=\"getHisCallEnd\"/>\n"
"    <signal name=\"incomingCall\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"comingValue\"/>\n"
"    </signal>\n"
"    <signal name=\"outgoingCall\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"outgoingValue\"/>\n"
"    </signal>\n"
"    <signal name=\"changeCallTime\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"timeValue\"/>\n"
"    </signal>\n"
"    <signal name=\"connectCall\"/>\n"
"    <signal name=\"endingCall\"/>\n"
"    <signal name=\"connectEd\"/>\n"
"    <signal name=\"requestBtPhoneAudioSource\"/>\n"
"    <signal name=\"startOutgoingCall\"/>\n"
"    <signal name=\"startIncomingCall\"/>\n"
"    <signal name=\"answerCall\"/>\n"
"  </interface>\n"
        "")
public:
    TcBtPhoneAdaptor(QObject *parent);
    virtual ~TcBtPhoneAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void cmdChangeVoiceMode();
    void cmdDialByName(const QString &contactName, int numSize);
    void cmdDialByNum(const QString &contactPhNum, int numSize);
    void cmdEndCal();
    void cmdHangUp();
    void cmdIncomingAnswer();
    void cmdIncomingReject();
    void cmdNumBtnClicked(int Num);
    void cmdOpenPhoneAudio();
    void cmdReDial();
    void cmdSetVoiceMute();
    void cmdStartIncomingCall();
    void cmdStartOutgoingCall();
    void cmdVoiceRecognition();
    void deviceAllDelete();
    void deviceCompareornot(bool bAccept);
    void deviceConnect(int DeviceNum);
    void deviceDelete(int DeviceNum);
    void deviceDisconnect(int DeviceNum);
    void deviceSearchCancel();
    void deviceSearchStart(int totalSearchTime, int maxDevices);
    void getContactInfo();
    void getHistoryCalInfo();
    void sysActivate();
    void sysDeactivate();
Q_SIGNALS: // SIGNALS
    void answerCall();
    void changeCallTime(const QString &timeValue);
    void connectCall();
    void connectEd();
    void deInitBtappSuccess();
    void deviceCompare(const QString &deviceName, const QString &passCode, const QString &deviceAddr);
    void deviceConnectFaile();
    void deviceConnectSuccess(const QString &deviceName, const QString &deviceAddr);
    void deviceDeleteSuccess();
    void deviceDisConnectSuccess();
    void deviceSearchClosed();
    void deviceSearchSuccess(const QString &deviceName);
    void endingCall();
    void getContactsEnd();
    void getContactsFaile();
    void getContactsSuccess(const QString &contactName, const QString &homeNum, const QString &workNum, const QString &otherNum);
    void getHisCallEnd();
    void getHisCallFaile();
    void getHisCallSuccess(const QString &hisCallname, const QString &hisCallnum, const QString &hisCalltime, int hisCalltype);
    void incomingCall(const QString &comingValue);
    void initBtappFaile();
    void initBtappSuccess(const QString &deviceName, const QString &deviceAddr);
    void outgoingCall(const QString &outgoingValue);
    void requestBtPhoneAudioSource();
    void startIncomingCall();
    void startOutgoingCall();
};

#endif
