/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a tcbtmusic_adaptor.h: ../dbus_xml_config/Semisky.BlueToothMidware.TcBtMusic.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TCBTMUSIC_ADAPTOR_H
#define TCBTMUSIC_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface smk.tcc8971.BlueToothMidware.TcBtMusic
 */
class TcBtMusicAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "smk.tcc8971.BlueToothMidware.TcBtMusic")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"smk.tcc8971.BlueToothMidware.TcBtMusic\">\n"
"    <method name=\"requeseBtMusicAudioSource\"/>\n"
"    <method name=\"closeBtMusic\"/>\n"
"    <method name=\"playStart\"/>\n"
"    <method name=\"playStop\"/>\n"
"    <method name=\"playNext\"/>\n"
"    <method name=\"playPre\"/>\n"
"    <method name=\"playFF\"/>\n"
"    <method name=\"playRew\"/>\n"
"    <method name=\"SetRepeatMode\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"    </method>\n"
"    <method name=\"SetShuffleMode\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"    </method>\n"
"    <signal name=\"avSinkConnected\"/>\n"
"    <signal name=\"avSinkDisConnected\"/>\n"
"    <signal name=\"getMetaDataTitle\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"title\"/>\n"
"    </signal>\n"
"    <signal name=\"getMetaDataArtist\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"artist\"/>\n"
"    </signal>\n"
"    <signal name=\"getMetaDataAlbum\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"album\"/>\n"
"    </signal>\n"
"    <signal name=\"getMetaDataGenre\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"genre\"/>\n"
"    </signal>\n"
"    <signal name=\"getMetaDataTrack\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"track\"/>\n"
"    </signal>\n"
"    <signal name=\"getTotalLength\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"length\"/>\n"
"    </signal>\n"
"    <signal name=\"getCurrentPostion\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"postion\"/>\n"
"    </signal>\n"
"    <signal name=\"getPlayStatus\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </signal>\n"
"    <signal name=\"getTotalTime\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </signal>\n"
"    <signal name=\"changeRepeatMode\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"mode\"/>\n"
"    </signal>\n"
"    <signal name=\"changeShuffleMode\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"mode\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    TcBtMusicAdaptor(QObject *parent);
    virtual ~TcBtMusicAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void SetRepeatMode(int mode);
    void SetShuffleMode(int mode);
    void closeBtMusic();
    void playFF();
    void playNext();
    void playPre();
    void playRew();
    void playStart();
    void playStop();
    void requeseBtMusicAudioSource();
Q_SIGNALS: // SIGNALS
    void avSinkConnected();
    void avSinkDisConnected();
    void changeRepeatMode(int mode);
    void changeShuffleMode(int mode);
    void getCurrentPostion(int postion);
    void getMetaDataAlbum(const QString &album);
    void getMetaDataArtist(const QString &artist);
    void getMetaDataGenre(const QString &genre);
    void getMetaDataTitle(const QString &title);
    void getMetaDataTrack(int track);
    void getPlayStatus(int status);
    void getTotalLength(int length);
    void getTotalTime(int status);
};

#endif
